refactor(jakarta): migrate from javax to jakarta packages for Spring Boot 3 compatibility Addressed build failure by replacing jakarta with javax. This issue arises as Spring Boot 3 now relies on Jakarta packages instead of javax.
Error:
```
igor/igor-core/src/main/java/com/netflix/spinnaker/igor/artifacts/JinjaTemplateService.java:21: error: cannot find symbol
import javax.annotation.PostConstruct;
                       ^
  symbol:   class PostConstruct
  location: package javax.annotation
igor/igor-core/src/main/java/com/netflix/spinnaker/igor/polling/CommonPollingMonitor.java:35: error: cannot find symbol
import javax.annotation.PreDestroy;
```
Reference Links:
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#jakarta-ee