refactor(jakarta): migrate from javax to jakarta packages for Spring Boot 3 compatibility Addressed build failure by replacing jakarta with javax. This issue arises as Spring Boot 3 now relies on Jakarta packages instead of javax.
```
Attached a portion of error logs for reference:
igor/igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/GitlabCiProperties.java:21: error: package javax.validation does not exist
import javax.validation.Valid;
                       ^
igor/igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/GitLabConfig.java:23: error: package javax.validation does not exist
import javax.validation.Valid;
                       ^
igor/igor-web/src/main/groovy/com/netflix/spinnaker/igor/config/GitLabProperties.java:19: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotNull;
                                   ^
igor/igor-web/build/tmp/compileGroovy/groovy-java-stubs/com/netflix/spinnaker/igor/config/JenkinsProperties.java:8: error: package javax.validation does not exist
import javax.validation.Valid;
                       ^
igor/igor-web/src/main/java/com/netflix/spinnaker/igor/config/ConcourseConfig.java:14: error: package javax.validation does not exist
import javax.validation.Valid;
                       ^
igor/igor-web/build/tmp/compileGroovy/groovy-java-stubs/com/netflix/spinnaker/igor/config/BitBucketProperties.java:10: error: package javax.validation does not exist
  extends java.lang.Object  implements
    ^
igor/igor-web/build/tmp/compileGroovy/groovy-java-stubs/com/netflix/spinnaker/igor/config/BitBucketProperties.java:7: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotNull;
```

Reference Links:
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#jakarta-ee