refactor(security): Replaced the use of WebSecurityConfigurerAdapter with a configuration that defines SecurityFilterChain bean. The error occurs because WebSecurityConfigurerAdapter has been deprecated and removed in Spring Security 6.x, which is used by Spring Boot 3.x.
Error details for reference:
```
igor/igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildTest.java:61: error: cannot find symbol
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
                                                                       ^
  symbol:   class WebSecurityConfigurerAdapter
  location: package org.springframework.security.config.annotation.web.configuration
/home/rahul/Documents/codebase/spinnaker/igor/igor-web/src/test/groovy/com/netflix/spinnaker/igor/gcb/GoogleCloudBuildTest.java:96: error: cannot find symbol
  static class WebSecurityConfig extends WebSecurityConfigurerAdapter {
                                         ^
  symbol:   class WebSecurityConfigurerAdapter
  location: class GoogleCloudBuildTest
2 errors
startup failed:
```
Reference:
https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter