refactor(jakarta): migrate from javax to jakarta packages for Spring Boot 3 compatibility
Addressed build failure by replacing jakarta with javax. This issue arises as Spring Boot 3 now relies on Jakarta packages instead of javax.

```
Attached a portion of error logs for reference:
igor/igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/config/TravisProperties.java:25: error: package javax.validation does not exist
import javax.validation.Valid;
                       ^
igor/igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/config/TravisProperties.java:26: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotEmpty;

igor/igor-monitor-travis/src/main/java/com/netflix/spinnaker/igor/travis/config/TravisConfig.java:38: error: package javax.validation does not exist
import javax.validation.Valid;

```
Reference Links:
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#jakarta-ee